language: php

php:
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - composer selfupdate

install:
  - composer update --prefer-dist --no-interaction

script:
  - cd ./bin/scripts \
    && sh travis_phpunit.sh \
    && sh travis_coverfish.sh \
    && sh travis_coverage.sh \
    && sh scrutinizer_ccup.sh \
    && cd ../../

notifications:
  email:
    - patrick.paechnatz@gmail.com
    - dunkelfrosch.net@gmail.com
