language: php

php:
  - 5.5

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - composer selfupdate

install:
    - composer update --prefer-dist --no-interaction

script:
    - cd bin/scripts & sh ./travis_phpunit.sh & ./travis_coverfish.sh & ./travis_coverage.sh & ./scrutinizer_ccup.sh & cd ../../

notifications:
  email:
    - patrick.paechnatz@gmail.com
    - dunkelfrosch.net@gmail.com