language: php

php:
  - 5.4
  - 5.5

install:
   - composer selfupdate
   - composer install

script: phpunit --testdox --configuration phpunit.xml

notifications:
  email:
    - patrick.paechnatz@gmail.com
    - dunkelfrosch.net@gmail.com