language: php

php:
  - 5.5
  # - 5.6

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - composer selfupdate

install:
    - composer update --prefer-dist --no-interaction

script:
    - cd ./bin/scripts && sh travis_phpunit.sh
    - cd ./bin/scripts && sh travis_coverfish.sh
    - cd ./bin/scripts && sh travis_coverage.sh
    # - sh ./bin/scripts/scrutinizer_ccup.sh

notifications:
  email:
    - patrick.paechnatz@gmail.com
    - dunkelfrosch.net@gmail.com