language: php

php:
  - 5.5

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - composer selfupdate

install: composer update --prefer-dist --no-interaction

script: phpunit --debug --configuration ./Tests/phpunit.xml

notifications:
  email:
    - patrick.paechnatz@gmail.com
    - dunkelfrosch.net@gmail.com